[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
proof_of_engagement = "DGMwn7z9fqvaDVXy7tuiXcjvUT8T94Hz5VuTyYo2RPGn"

[programs.devnet]
proof_of_engagement = "5cCUfaLSDyNMV21cYsMgBrvVfm8JVNTVzVWcFY2V7R8t"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/mpl_token_metadata.so"
