[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
proof_of_engagement = "HifshiXvDF4MwEevZuukURThkjrZFfspn3iP1vdFitdC"

[programs.devnet]
proof_of_engagement = "HifshiXvDF4MwEevZuukURThkjrZFfspn3iP1vdFitdC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "tests/fixtures/mpl_token_metadata.so"
